spring:
  application:
    name: chatsrv
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: chat_srv_db
      authentication-database: admin
server:
  port: 8088
